receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'

processors:
  batch:

exporters:

  otlphttp:
    endpoint: http://jaeger-ui:4318
    tls:
      insecure: true

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9464

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
